/**
 * PARABLE — watermarked “sample / demo” CFO summary HTML for print-to-PDF
 * Pairs with `public/samplePdfStyles.css` and `body.parable-sample-export`.
 * @module exportSampleSummary
 */

/**
 * @typedef {{
 *   year: number;
 *   orgName: string;
 *   resolutionDate: string;
 *   totalDeposits: string | number;
 *   eftpsMatchLine?: string;
 *   governanceLine?: string;
 *   ubiStatus?: string;
 *   form941QuartersText?: string;
 *   stylesOrigin?: string;
 * }} SamplePdfPayload
 */

const esc = (s) => String(s ?? "")
  .replace(/&/g, "&amp;")
  .replace(/</g, "&lt;")
  .replace(/"/g, "&quot;");

/**
 * Full HTML5 document. Opens in a new window, then `print()`.
 * @param {SamplePdfPayload} demoData
 * @returns {string}
 */
export function generateSamplePdf(demoData) {
  const {
    year,
    orgName,
    resolutionDate,
    totalDeposits,
    eftpsMatchLine = "(modeled 100% match to tagged bank lines)",
    governanceLine = "Governance artifacts on file (demo seed).",
    ubiStatus = "Modeled from ledger UBI tags.",
    form941QuartersText = "Q1–Q4 workpaper state from quarterly_tax_reports + ledger",
    stylesOrigin = "",
  } = demoData || {};

  const origin = stylesOrigin && typeof stylesOrigin === "string" && stylesOrigin.length
    ? stylesOrigin.replace(/\/$/, "")
    : "";
  const cssLink = origin ? `${origin}/samplePdfStyles.css` : "/samplePdfStyles.css";
  const depLabel = typeof totalDeposits === "number" ? totalDeposits.toFixed(2) : String(totalDeposits);

  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>SAMPLE — CFO compliance summary — ${esc(year)}</title>
  <link rel="stylesheet" href="${cssLink}" crossorigin="anonymous" />
  <style>
    /* fallback if /samplePdfStyles.css not reachable */
    body.parable-sample-export { margin:0; background:#050505; color:#f5f5f5; font-family: system-ui, sans-serif; }
    body.parable-sample-export .watermark-text {
      position:absolute; top:45%; left:50%;
      transform: translate(-50%,-50%) rotate(-32deg);
      font-size: 72px; font-weight: 900; color: rgba(255,255,255,0.04);
      text-transform: uppercase; letter-spacing: 0.35em; pointer-events: none;
    }
    body.parable-sample-export .content-layer { position: relative; z-index: 1; }
  </style>
</head>
<body class="parable-sample-export is-demo" data-print-demo="1">
  <div class="watermark-container" style="background: #050505; color: white; padding: 0;">
    <div class="watermark-text" aria-hidden="true">SAMPLE / DEMO</div>
    <div class="watermark-sublime" aria-hidden="true">ONLY</div>
    <div class="content-layer" style="padding: 0 0 0 0;">
      <p class="sample-banner">SAMPLE / DEMO ONLY — not for IRS filing or legal reliance</p>
      <p style="opacity:0.75;font-size:0.7rem;letter-spacing:0.1em;">${esc(orgName)}</p>
      <header style="border-left: 4px solid #22d3ee; padding-left: 20px; margin: 0 0 2rem 0;">
        <h1>CFO compliance summary (illustrative)</h1>
        <p style="opacity:0.6;margin:0.25rem 0 0 0;">Fiscal year: ${esc(year)}</p>
      </header>

      <section style="margin-bottom: 1.5rem;">
        <h2>Governance</h2>
        <p>${esc(governanceLine)}</p>
        <p>Housing allowance resolution (mock): SIGNED &mdash; ${esc(resolutionDate)}</p>
        <p>Accountable plan: ACTIVE (illustrative)</p>
      </section>

      <section style="margin-bottom: 1.5rem;">
        <h2>Tax (modeled)</h2>
        <p>Form 941 quarters: ${esc(form941QuartersText)}</p>
        <p>EFTPS deposits (tagged): $${esc(depLabel)} &mdash; ${esc(eftpsMatchLine)}</p>
        <p>${esc(ubiStatus)}</p>
      </section>

      <div class="certified-seal">
        PARABLE<br>LEDGER<br>Sample
      </div>

      <p class="foot">Generated by PARABLE demo data. This document is a visual sample. Go live to connect real systems and your CPA. Not tax or legal advice.</p>
    </div>
  </div>
</body>
</html>`;

  if (typeof console !== "undefined" && console.log) {
    console.log("PARABLE: watermarked sample CFO PDF shell ready (print in browser).");
  }
  return htmlContent;
}

/**
 * @param {SamplePdfPayload} demoData
 * @param {{ w?: Window }} [opt]
 * @returns {void}
 */
export function openSamplePdfPrint(demoData, opt) {
  const w = (opt && opt.w) || (typeof window !== "undefined" ? window.open("", "_blank") : null);
  if (!w) return;
  const d = { ...demoData, stylesOrigin: (typeof window !== "undefined" && window.location) ? window.location.origin : "" };
  w.document.open();
  w.document.write(generateSamplePdf(d));
  w.document.close();
  w.focus();
  w.print();
}
